### ISSUE TITLE
✨ NFT Collection: SECTION 2 - Lesson_4_Create_A_Contract_That_Mints_NFTs.md

### ISSUE THREAD

**Issue by HariMahesh** [buildspace/buildspace-projects#113]
! small syntax fix needed in the instructions. Need to add the ";" to the end of the new 4 lines to call makeAnEpicNFT function, or else the makeAnEpicNFT function doesn't run.

<img width="489" alt="Screen Shot 2021-10-09 at 6 44 26 PM" src="https://user-images.githubusercontent.com/8985764/136678663-618fa36c-ac9c-4190-8a81-6cfc5c653288.png">

**Comment by adilanchian** [comment]
@HariMahesh -

If you come across this issue again, feel free to open up a PR for it :). Thanks for the heads up!
