### ISSUE TITLE
Build a Web3 app on Solana with React and Rust: SECTION_4 - Call deployed program from web app

### ISSUE THREAD

**Issue by mrsaifullah52** [buildspace/buildspace-projects#1140]
`import { Program, Provider, web3 } from '@project-serum/anchor';`

this import statement should have to be replaced with the below statement

`import { Program, AnchorProvider as Provider, web3 } from '@project-serum/anchor';`

anchor team has made changes, the current import statement in the lesson triggering an error:
`export ‘Provider’ (imported as ‘Provider’) was not found in ‘[@project](http://twitter.com/project)-serum/anchor’`

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
