### ISSUE TITLE
✨ Solana_Pay_Store: SECTION_2 - Lesson_3_Turn_Transactions_to_Payments

### ISSUE THREAD

**Issue by kaleabMelkamu** [buildspace/buildspace-projects#1190]
### Forget to Change Phantom wallet to Devnet
  Issue: 
  `{code: -32003, message: 'failed to send transaction: Transaction simulation failed: Blockhash not found'}`
 
 -Before making transaction You need to make sure our wallet is in Devnet, otherwise we won't be able to 
  make any transaction
 -To solve this

-    Open our phantom wallet setting
-    Then to Change Network and select the Devnet Network
-    Done😎

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
