### ISSUE TITLE
A better way to deploy Ethereum Smart Contracts - thirdweb deploy

### ISSUE THREAD

**Issue by vijethx** [buildspace/buildspace-projects#1207]
Discovered this interesting [video](https://www.youtube.com/watch?v=CaODHRnFgBw) by Dhaiwat yesterday. 

This might solve the problem of accidentally committing private keys to Github. It'd be awesome if the deployers are given an option to choose between the current .env file method or this method

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
