### ISSUE TITLE
✨ [Polygon_ENS]: <SECTION_1> - <Lesson_1_Get_Local_Ethereum_Running>

### ISSUE THREAD

**Issue by RV12R** [buildspace/buildspace-projects#1209]
### What You Are Changing
*When i run "npx hardhat" There was no option like “Create a basic sample project” I think its outdated.*

### Anything else?
*Any other thoughts or concerns? Let us know!*

**Comment by RV12R** [comment]
Hardhat has updated their libraries. that's why its showing

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.

**Comment by Alekhyadaspet** [comment]
@RV12R Could you update steps in https://buildspace.so/p/build-polygon-ens/lessons/running-basic-smart-contract to generate the expected output. I tried with the latest solidity version 0.8.17, and it still wont run. The debug message says : hre is not defined". 
![Screenshot 2022-12-17 at 8 30 36 PM](https://user-images.githubusercontent.com/9607118/208248103-c053917e-de36-4f2e-b9e4-71895ae33a88.png)
The Terminal command npx hardhat run scripts/run.js doesnt print any output. 
I'm new to node.js, I'm more of a [python person], started node.js recently. 
It would be helpful if you could specify how running and debugging, versioning, etc can be managed from VSCode itself or detail steps to debug from terminal.

Many thanks.
