### ISSUE TITLE
✨ [Solana NFT Metaplex]

### ISSUE THREAD

**Issue by priyansh71** [buildspace/buildspace-projects#1227]
I was thinking of shifting the project from using the Metaplex CLI from their official repository to using their official Rust-based candy machine CLI called [Sugar](https://github.com/metaplex-foundation/sugar). It is not only easier to set up all devices but also gives fewer errors, besides being well-maintained. 

Moreover, to make the project more exciting and provide an insight to the builders on why NFTs in Solana are so complex, I was thinking of adding thrilling reads like the one linked [here](https://lorisleiva.com/owning-digital-assets-in-solana/how-nfts-are-represented-in-solana).

The project starter code, precisely the one in the file ```connection.js```, needs to be changed a bit because it leads to an unsolvable error which kind of demotivates everyone. The only way to solve that issue is by roaming around Metaplex's discords and finding the correct codebase source, which is [this](https://github.com/metaplex-foundation/candy-machine-ui).

https://user-images.githubusercontent.com/77532581/180922644-2861b96e-acbb-4d97-989b-1e07b2275495.mov

However, this codebase is much more complex, typescript based, and would be difficult to break into starter project files. I 
Hence, I plan to revamp the starter codebase and some of the lesson contents, so these issues do not pop up.
Update: I created an [NPM package](https://www.npmjs.com/package/candy-machine-assistant) to use the required functions directly!

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
