### ISSUE TITLE
✨ [solana-core]: <core 1> - <Lesson_11_Build_NFT_Minter_Frontend.md>

### ISSUE THREAD

**Issue by scheuclu** [buildspace/buildspace-projects#1320]
I followed the exact guideline on the lesson and cross checked it multiple times.

When including the Navbar in index.tsx, I get the following error:
https://tinyurl.com/2b7me358

If I go to NavBar.txt and change it to
```
...
    <HStack width="full" padding={4}>
      <Spacer />
      {/* <WalletMultiButton className={styles["wallet-adapter-button-trigger"]} /> */}
    </HStack>
...
```
the error disappears.
So it must have to do with `WalletMultiButton`.

**Comment by helloitsm3** [comment]
Are you still having this issue? Can you try installing the latest packages and see if that helps?
