### ISSUE TITLE
✨ [solana-core]: core1 - Lesson_11_Build_NFT_Minter_Frontend.md

### ISSUE THREAD

**Issue by scheuclu** [buildspace/buildspace-projects#1321]
There seems to be a general issue with the code provided here, or some code is missing.
 The variable `connected` used in the code-updates for index.js has never been declared.

I think it would be super helpful to provide a link to the complete solution, as was the case in previous lessons.

**Comment by helloitsm3** [comment]
Here's the link to the solution https://github.com/helloitsm3/buildspace-solutions/tree/solana-core/core1
