### ISSUE TITLE
✨ Solana-Core: Core_2- Lesson_14_Displaying_NFTs_from_Wallet

### ISSUE THREAD

**Issue by scheuclu** [buildspace/buildspace-projects#1347]
I followed every step of the tutorial.

Yet, instead of a functioning webpage that displays NFTs, I get the following error.
```
WebSocket connection to 'ws://localhost:3000/_next/webpack-hmr' failed: 
   init | @ | websocket.js?a9be:46
```

The error happens in Chrome, Brave as well as Firefox.
Google searching suggests it may be down to package version conflicts.

Unfortunately, I am not skilled enough in Javascript to debug this myself.

**Comment by helloitsm3** [comment]
It seems like your browser is blocking websocket connection. Are you using any anti-websocket extension?
