### ISSUE TITLE
✨ [Solana_Core]: <SECTION_2> - <Lesson_13_Displaying_NFTs.md>

### ISSUE THREAD

**Issue by shungo0222** [buildspace/buildspace-projects#1382]
### What You Are Changing
I think you don't need to add `run()`.
![Screen Shot 2022-11-19 at 15 14 55](https://user-images.githubusercontent.com/54393289/202837793-78fc3f3c-6936-496a-8915-d88dd6775463.png)
Because of this doc of the latest version. [https://metaplex-foundation.github.io/js/classes/js.NftClient.html#findAllByOwner](https://metaplex-foundation.github.io/js/classes/js.NftClient.html#findAllByOwner)

**Comment by helloitsm3** [comment]
This is already solved in one of the PRs
