### ISSUE TITLE
✨ [Solana_Core]: <SECTION_2> - <Lesson_15_Display_NFTs_From_Candy_Machine.md>

### ISSUE THREAD

**Issue by shungo0222** [buildspace/buildspace-projects#1384]
### What You Are Changing
I think you don't need to add `run()` and change from `candyMachines()` to `candyMachinesV2()`.
![Screen Shot 2022-11-19 at 15 57 32](https://user-images.githubusercontent.com/54393289/202838954-789d30e6-4db0-43e6-9ad9-a956b08caeee.png)
Because of this doc of the latest version. https://metaplex-foundation.github.io/js/classes/js.CandyMachinesV2Client.html#findByAddress

**Comment by helloitsm3** [comment]
This was fix here #1375
