### ISSUE TITLE
✨ [GPT-3 Writer]: <SECTION_2> - <Add_in_the_OpenAI_API

### ISSUE THREAD

**Issue by Raphael-Quinones** [buildspace/buildspace-projects#1416]
### What You Are Changing
"this will be where we story the output of the API we want to show the user"

this particular phrase has the wrong use of the word "story". I think it's supposed to be "store"

"this will be where we store the output of the API we want to show the user"
### Anything else?
*Sorry about the petty issue request*

**Comment by helloitsm3** [comment]
Fixed in #1425
