### ISSUE TITLE
✨ [JS_DAO]: <SECTION_1> - <Add Wallet to Dashboard>

### ISSUE THREAD

**Issue by Atharv181** [buildspace/buildspace-projects#1430]
### What You Are Changing
*A short description of the change you made and why!*
Not able to connect the wallet to the site. Getting the error "Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@thirdweb-dev_react.js?v=ea05feb8' does not provide an export named 'ConnectWallet' " 
Might the problem with thirdweb

### Anything else?
*Any other thoughts or concerns? Let us know!*

**Comment by helloitsm3** [comment]
Have you tried updating your thirdweb library to the latest version?
