### ISSUE TITLE
✨ [GPT3_Writer]: <SECTION_3> - <Lesson_3_Inject_into_webpage>

### ISSUE THREAD

**Issue by NemesisLW** [buildspace/buildspace-projects#1440]
### ISSUE
The process of finding the active tab is a little weird. It doesn't work if we change focus from the text-editor tab to another tab or the service worker console. Code errors out with Error messages like -
 `Error handling response: TypeError: Cannot read properties of undefined (reading 'status');
TypeError: Cannot read properties of undefined (reading ''id')`.

There should be a better way to implement this.

**Comment by NemesisLW** [comment]
`chrome.tabs.query({ url: "URL_of_your_text_editor" }, (tabs) => {
    const activeTab = tabs[0].id;`. works. But shouldn't be the idea solution.

**Comment by shabbiryk** [comment]
Hey, could you assign me this issue?

**Comment by NemesisLW** [comment]
> @NemesisLW were you able to find an alternative to this?

I used the `url` parameter to point to the text-editor directly, `chrome.tabs.query({ url: "URL_of_your_text_editor" }, (tabs) => { const activeTab = tabs[0].id;` instead of the `chrome.tabs.query({ active: true, currentWindow: true }` suggested in the build. It solved the focusing out of the currentWindow issue.

**Comment by helloitsm3** [comment]
> > @NemesisLW were you able to find an alternative to this?
> 
> I used the `url` parameter to point to the text-editor directly, `chrome.tabs.query({ url: "URL_of_your_text_editor" }, (tabs) => { const activeTab = tabs[0].id;` instead of the `chrome.tabs.query({ active: true, currentWindow: true }` suggested in the build. It solved the focusing out of the currentWindow issue.

Great! If you think this is helpful for the rest of the learners, you can consider creating a PR to add it to the lessons
