### ISSUE TITLE
✨ [Build a GPT3 Writer]: <SECTION_3> - <Call OpenAI from your extension>

### ISSUE THREAD

**Issue by Raphael-Quinones** [buildspace/buildspace-projects#1441]
### What You Are Changing
*Afterwords, you’ll be able to use the same flow for whatever website you want to generate text on.*

I think "Afterwords" should be "Afterwards"

### Anything else?
*Any other thoughts or concerns? Let us know!*

**Comment by helloitsm3** [comment]
Feel free to create a PR to fix this change
