### ISSUE TITLE
✨ [JS_DAO]: <SECTION_#2> - <Lesson_3_Let_Users_Mint_Your_NFT>

### ISSUE THREAD

**Issue by Atharv181** [buildspace/buildspace-projects#1464]
### What You Are Changing
*A short description of the change you made and why!*
We need to add the editiondrop address in double quotes

![image](https://user-images.githubusercontent.com/73999654/206767841-6d2b997e-2fe7-4091-919a-4e2854338adc.png)

**Comment by helloitsm3** [comment]
You need to either create a variable named `editionDropAddress` or replace it with your own `address`. Like this

```javascript
const editionDropAddress = "";
contractAddress={editionDropAddress}
```
