### ISSUE TITLE
✨ [Build a DAO]: <Grab the code and setup>

### ISSUE THREAD

**Issue by scenaristeur** [buildspace/buildspace-projects#1525]
### What You Are Changing
the source https://replit.com/@thirdweb/buildspace-dao-starter-v3?utm_source=buildspace.so&utm_medium=buildspace_project is not exactly the same as the one on github https://github.com/buildspace/buildspace-dao-starter?utm_source=buildspace.so&utm_medium=buildspace_project

on replit, we've got an index.jsx with different content
 
and on localhost , with node 16.19.0 when running "npm run start" i got a lot of messages like this 

``WARNING in ./node_modules/@walletconnect/jsonrpc-types/dist/esm/misc.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/smag/dev/buildspace-dao-starter/node_modules/@walletconnect/jsonrpc-types/src/misc.ts' file: Error: ENOENT: no such file or directory, open '/home/smag/dev/buildspace-dao-starter/node_modules/@walletconnect/jsonrpc-types/src/misc.ts'
 @ ./node_modules/@walletconnect/jsonrpc-types/dist/esm/index.js 2:0-23 2:0-23
 @ ./node_modules/@walletconnect/signer-connection/dist/esm/index.js 4:0-66 6:38-56
 @ ./node_modules/@walletconnect/ethereum-provider/dist/esm/index.js 5:0-68 13:42-58
 @ ./node_modules/wagmi-core/connectors/walletConnect/dist/wagmi-core-connectors-walletConnect.esm.js 3:0-69 97:102-123
 @ ./node_modules/wagmi/connectors/walletConnect/dist/wagmi-connectors-walletConnect.esm.js 1:0-77 1:0-77
 @ ./node_modules/@thirdweb-dev/react/dist/thirdweb-dev-react.esm.js 9:0-40
 @ ./src/index.js 10:0-55 21:33-49

WARNING in ./node_modules/@walletconnect/jsonrpc-types/dist/esm/provider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/smag/dev/buildspace-dao-starter/node_modules/@walletconnect/jsonrpc-types/src/provider.ts' file: Error: ENOENT: no such file or directory, open '/home/smag/dev/buildspace-dao-starter/node_modules/@walletconnect/jsonrpc-types/src/provider.ts'
 @ ./node_modules/@walletconnect/jsonrpc-types/dist/esm/index.js 3:0-27 3:0-27
 @ ./node_modules/@walletconnect/signer-connection/dist/esm/index.js 4:0-66 6:38-56
 @ ./node_modules/@walletconnect/ethereum-provider/dist/esm/index.js 5:0-68 13:42-58
 @ ./node_modules/wagmi-core/connectors/walletConnect/dist/wagmi-core-connectors-walletConnect.esm.js 3:0-69 97:102-123
 @ ./node_modules/wagmi/connectors/walletConnect/dist/wagmi-connectors-walletConnect.esm.js 1:0-77 1:0-77
 @ ./node_modules/@thirdweb-dev/react/dist/thirdweb-dev-react.esm.js 9:0-40
 @ ./src/index.js 10:0-55 21:33-49

``

**Comment by helloitsm3** [comment]
Try deleting `package-lock.json` and `node_modules` then run `npm install`.

**Comment by scenaristeur** [comment]
just deleted package-lock & node_modules, but it's the same

**Comment by helloitsm3** [comment]
Try referring to this solution and see if it helps. https://github.com/helloitsm3/buildspace-solutions/tree/build-your-own-dao

**Comment by helloitsm3** [comment]
Was this helpful? @scenaristeur
