### ISSUE TITLE
✨ [BUILD A DAO]: <error scripts/7-airdrop-token.js> Failed to airdrop tokens Error: eth_getLogs and eth_newFilter are limited to a 10,000 blocks range

### ISSUE THREAD

**Issue by scenaristeur** [buildspace/buildspace-projects#1526]
### What You Are Changing
Hello, I got an error with scripts/7-airdrop-token.js

it seems to be related to Quicknode https://support.quicknode.com/hc/en-us/articles/10258449939473-Is-there-a-block-range-limit-for-querying-logs-and-events-

node scripts/7-airdrop-token.js
👋 SDK initialized by address: 0x64A7590c141ADC0AddDf7cb018e65379040356bA
Failed to airdrop tokens Error: eth_getLogs and eth_newFilter are limited to a 10,000 blocks range
    at /home/smag/dev/buildspace-dao-starter/node_modules/@ethersproject/providers/lib/json-rpc-batch-provider.js:72:41
    at Array.forEach (<anonymous>)
    at /home/smag/dev/buildspace-dao-starter/node_modules/@ethersproject/providers/lib/json-rpc-batch-provider.js:69:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: -32602,
  data: undefined
}

with this airdrop code 
``
import sdk from "./1-initialize-sdk.js";

(async () => {
  try {
    // This is the address to our ERC-1155 membership NFT contract.
    const editionDrop = await sdk.getContract("0x4B69D23FC8ffB198895f20A75C8E0322B87E36CF", "edition-drop");
    // This is the address to our ERC-20 token contract.
    const token = await sdk.getContract("0x772c569F9E3B43F768a69d2CaC6DaCAA3A5c7827", "token");
    // Grab all the addresses of people who own our membership NFT, which has
    // a tokenId of 0.
    const walletAddresses = await editionDrop.history.getAllClaimerAddresses(0);

    if (walletAddresses.length === 0) {
      console.log(
        "No NFTs have been claimed yet, maybe get some friends to claim your free NFTs!",
      );
      process.exit(0);
    }

    // Loop through the array of addresses.
    const airdropTargets = walletAddresses.map((address) => {
      // Pick a random # between 1000 and 10000.
      const randomAmount = Math.floor(Math.random() * (10000 - 1000 + 1) + 1000);
      console.log("✅ Going to airdrop", randomAmount, "tokens to", address);

      // Set up the target.
      const airdropTarget = {
        toAddress: address,
        amount: randomAmount,
      };

      return airdropTarget;
    });

    // Call transferBatch on all our airdrop targets.
    console.log("🌈 Starting airdrop...");
    await token.transferBatch(airdropTargets);
    console.log("✅ Successfully airdropped tokens to all the holders of the NFT!");
  } catch (err) {
    console.error("Failed to airdrop tokens", err);
  }
})();

```

**Comment by helloitsm3** [comment]
Use [Alchemy](https://alchemy.com/) instead of Quicknode. It'll solve this issue
