### ISSUE TITLE
Couldn't Create a Tweet

### ISSUE THREAD

**Issue by simplysabir** [buildspace/buildspace-projects#1591]
In Solana Core Module, I'm Getting this Error
![tGak15T](https://user-images.githubusercontent.com/76485932/216798203-b37a5284-846f-48d4-a463-2d215876f895.png)

also i would like to work on this issue

**Comment by helloitsm3** [comment]
> In Solana Core Module, I'm Getting this Error ![tGak15T](https://user-images.githubusercontent.com/76485932/216798203-b37a5284-846f-48d4-a463-2d215876f895.png)
> 
> also i would like to work on this issue

This is due to the limitation of the API

**Comment by simplysabir** [comment]
okay, i guess i should close this issue then
