### ISSUE TITLE
✨ [Intro to Solidity: Ship an Ethereum dApp]: <1> - <Get your local Ethereum networking running>

### ISSUE THREAD

**Issue by Heph789** [buildspace/buildspace-projects#1598]
### What You Are Changing
In the Solidity and Web3 project in section 1 under "Get your local Ethereum networking running", it tells us to run `npx hardhat accounts`, but this results in the following error. I believe that this command was taken out of the new version of hardhat.

![image](https://user-images.githubusercontent.com/20362850/217440992-9975a1f5-26b1-4d3b-baee-5a178c6a9433.png)

### Anything else?
*Any other thoughts or concerns? Let us know!*

**Comment by helloitsm3** [comment]
Thanks for this. The reason why it throws this error is because you currently don't have any tasks named `accounts` in your `hardhat.config.js`. Do refer to the solution here https://github.com/helloitsm3/buildspace-solutions/blob/create-your-first-smart-contract/my-wave-portal/hardhat.config.js
