### ISSUE TITLE
📚 Course Topic Submission: What problems does web3 solve?

### ISSUE THREAD

**Issue by rigdern** [buildspace/buildspace-projects#185]
### Course Topic
After taking this course, I'd like to be able to answer questions like:
- What problems do web3, cryptocurrencies, and blockchains solve?
- What is the essence of these technologies? What are their key properties?
- Suppose these technologies become mainstream solutions in the future. What might that future look like?
- What are some of the most promising applications of these technologies that have been released or are in development?

### Have You Taken a Course On This Topic Before
No

### Do You Want To Write This Course?
I'd be open to participating in discussion about the course design.

### Other Thoughts
I think it'd be useful to have a course like this that focuses on these kinds of bigger picture questions. If such a course isn't a good fit for buildspace, I think it'd be useful for buildspace to link to some resources that explore these kinds of questions.

**Comment by adilanchian** [comment]
Hey @rigdern !

Thanks for the heads up here :). Your answer here was great! This was exactly what I was looking for haha. We will keep this in mind while we go forward!!

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.

**Comment by rigdern** [comment]
@helloitsm3 is there a buildspace course that focuses on exploring these kinds of questions?

**Comment by helloitsm3** [comment]
> @helloitsm3 is there a buildspace course that focuses on exploring these kinds of questions?

I don't have anything in mind at the moment. If I ever come across anything useful, I'll definitely let you know

**Comment by rigdern** [comment]
@helloitsm3 should we reopen this issue or is buildspace not interested in having an issue to track a course on these kinds of questions?

**Comment by helloitsm3** [comment]
> @helloitsm3 should we reopen this issue or is buildspace not interested in having an issue to track a course on these kinds of questions?

Sure, go ahead an re-open this

**Comment by rigdern** [comment]
@helloitsm3 I don't think GitHub gives me the ability to reopen this issue.
