### ISSUE TITLE
✨ [NFT_Collection]: <SECTION_#1> - <Lesson_4_Create_A_Contract_That_Mints_NFTs>

### ISSUE THREAD

**Issue by karpovks** [buildspace/buildspace-projects#190]
### What You Are Changing
In the first code block
 ``` pragma solidity 0.8.0;```
Was throwing an error for me.  Adding a " ^ " and changing to 
 ``` pragma solidity ^0.8.0;```
Cleared this.

### Anything else?
Unsure if the required use of " ^ " is just a quirk of the language.

**Comment by adilanchian** [comment]
@karpovks @ratracegrad - 

Thanks for the in fo here!!

We have built everything on `0.8.0` and have used this as our stable version at the moment. So, we don't want to actually update the version to be `0.8.9`

**Comment by adilanchian** [comment]
I think for now we are going to keep this as is. If you have any questions / concerns here feel free to open up a PR with your 
changes!
