### ISSUE TITLE
Translate into spanish the Section_1-lesson_1 of Solidity_And_Smart_Contracts course

### ISSUE THREAD

**Issue by gelopfalconEdify** [buildspace/buildspace-projects#269]
Translate into spanish the Section_1-lesson_1 of Solidity_And_Smart_Contracts course

**Comment by adilanchian** [comment]
@jesinnott

Thanks for tagging this in your PR!

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
