### ISSUE TITLE
✨ NFT GAME: SECTION_3 - Building the Character Select Page

### ISSUE THREAD

**Issue by christpet** [buildspace/buildspace-projects#279]
### Add a note to reconnect wallet if you encounter the "Call revert exception" issue

- A bunch of people in discord had this "Call revert exception" bug and got really frustrated by it. 
- After a bunch of googling and testing, I realized it's an issue with the signer not being able to connect with the contract ABI. It happened because my metamask was on a different network while I was working on the project. [source](https://github.com/ethers-io/ethers.js/issues/1804#issuecomment-887770523)
- I fixed it by disconnecting my wallet then reconnecting on Rinkeby! 
- It would help folks to add a note somewhere in the lesson that if they see this error, they should do the same!
- Not sure if this is coming up later in the course, but would be useful add validation that [prompts the user to change network](https://stackoverflow.com/questions/68252365/how-to-trigger-change-blockchain-network-request-on-metamask) instead of throwing this error.

![image](https://user-images.githubusercontent.com/32476396/139226906-e93b0ef1-6454-4168-bfef-11f7bb01547d.png)

**Comment by adilanchian** [comment]
Hey @christpet -

This is SICK. Great catch and thanks for looking out for the community :). I haven't seen a PR for this just yet... Would you be open to make this change? Just open up a PR and we will make sure to get it in

**Comment by adilanchian** [comment]
Hey @christpet just throwing a ping here

**Comment by stevedsimkins** [comment]
Added the requested changes so we can close this issue! ✨

**Comment by adilanchian** [comment]
@stevedsimkins CHEERS TY <3
