### ISSUE TITLE
✨ NFT_GAME: SECTION_4 - Finishing Touches on the UI

### ISSUE THREAD

**Issue by santbob** [buildspace/buildspace-projects#281]
### What You Are Changing
The code to show the toast is using the state variable `boss` instead it should be `showToast`, fixed the same.

### Anything else?
*Created a PR for the same https://github.com/buildspace/buildspace-projects/pull/277*

**Comment by adilanchian** [comment]
Hey @santbob -

Got your PR and made some comments :)

Referencing here #277

**Comment by adilanchian** [comment]
Merged in! Thanks again :)
