### ISSUE TITLE
✨ [Solana Web3]: <SECTION_2> - < Lesson_1_Get_Local_Solana_Env_Running>

### ISSUE THREAD

**Issue by pfeifemc** [buildspace/buildspace-projects#334]
### Yarn is required to initialize the Solana project directory
Under the sub-section: "🏃‍♂️ Create a test project and run it" we're instructed to create a directory and initialize a Solana project using `anchor init myepicproject --javascript` - this cmd will partially fail if _the user does not have yarn installed_. The terminal will return: `Error: yarn install failed: No such file or directory (os error 2)`
⭐️ Recommend adding a line to install yarn if not yet installed: `npm install --global yarn` :)

**Comment by pfeifemc** [comment]
It's worth noting that the project directory will still be created with some Anchor files, but will be missing vital dependencies to call the provider rpc.

**Comment by adilanchian** [comment]
Hey @pfeifemc !

This is a fantastic catch!! I _believe_ this should be fixed. We added this in the instructions! Could you double check this in the lessons?

**Comment by pfeifemc** [comment]
Hey @adilanchian ! Should I be looking for this in a PR or in the live product? Do you mention yarn by name or more generally? On first pass in prod I'm not seeing anything about yarn but I could be looking in the wrong place. Thanks!

**Comment by adilanchian** [comment]
Hey @pfeifemc !

So sorry for the terribly late reply here. I would look for this in the live product / here in Github as they are both kept up to date :). If you see anything let me know!

**Comment by pfeifemc** [comment]
Y'all are busy people! I've validated this fix is in the current build and I'm closing this issue.
