### ISSUE TITLE
✨ [Solana Web3]: <SECTION_1> - <Building a connect wallet button with Phantom Wallet.>

### ISSUE THREAD

**Issue by hubdev4** [buildspace/buildspace-projects#363]
### What You Are Changing
*A short description of the change you made and why!*

This line breaks the UI, the 'container' isn't displayed at all. I had to comment to work fine, also div tag isn't closed.

<div className={walletAddress ? 'authed-container' : 'container'}/> 

### Anything else?
*Any other thoughts or concerns? Let us know!*

**Comment by adilanchian** [comment]
Hi @hubdev4 !

I'm not sure what line you are referring to. Also would you be open to just opening a PR with your change?

**Comment by hubdev4** [comment]
Hello, here you are
https://github.com/buildspace/buildspace-projects/pull/361

**Comment by adilanchian** [comment]
Ahh I see!! 

This actually seemed to be something more along the lines of some mismatched brackets on your end. Going to close this issue for now :)
