### ISSUE TITLE
✨ [Solana_And_Web3]: <Section_2> - <Lesson_2_Write_First_Solana_Program>

### ISSUE THREAD

**Issue by GrowthJeff** [buildspace/buildspace-projects#373]
### What You Are Changing
When performing `anchor test` for the first time on MacOS, I received the error message `Error: Cannot find module '@project-serum/anchor'` 

The fix for this is to add `export NODE_PATH="$(npm config get prefix)/lib/node_modules"` to your shell script config file and then source it 

`source ~/.zshrc`

I saw three other mentions of this in the Discord. I'll investigate an editorial change to the lesson to include a note on how to handle this error.
### Anything else?
*Any other thoughts or concerns? Let us know!*

**Comment by adilanchian** [comment]
Hey @GrowthJeff -

Thanks so much for the issue!! This seems a bit odd... shouldn't you just have to install the npm module here?

**Comment by adilanchian** [comment]
Going to go ahead and close this out :). If you have any questions or concerns feel free to open up another Issue / PR!
