### ISSUE TITLE
✨ Build a Web3 app on Solana with React and Rust: 2 - ☀️ Get local Solana env running.

### ISSUE THREAD

**Issue by alecchendev** [buildspace/buildspace-projects#394]
### What You Are Changing
- In the M1 solana install guide, I ran into an issue running `./scripts/cargo-install-all.sh .` even after installing coreutils. It was a problem with openssl.
- I installed openssl via `brew install openssl@1.1` as recommended by [this tutorial](https://dev.to/nickgarfield/how-to-install-solana-dev-tools-on-an-m1-mac-kfn)
- Got another error about linking. Implemented another thing by the same tutorial
   - adding the following to ~/.cargo/config
```
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```
- Then it worked

**Comment by adilanchian** [comment]
Hey @alecchendev !!

Would you be open to making a PR for this? Would be awesome!

Also - welcome to buildspace fellow Alec 🤘

**Comment by alecchendev** [comment]
For sure!

Thanks!

**Comment by adilanchian** [comment]
TY!
