### ISSUE TITLE
Translate into spanish the Section_1-lesson_2 of Solidity_And_Smart_Contracts

### ISSUE THREAD

**Issue by jesinnott** [buildspace/buildspace-projects#439]
Translate into spanish the Section 1 Lesson 2 of Solidity_And_Smart_Contracts.

I am not able to add the translate label.

**Comment by adilanchian** [comment]
Hey @jesinnott got you !

Thanks for tagging the issue in your PR as well :)

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
