### ISSUE TITLE
Translate into spanish the Section_1-lesson_3 of Solidity_And_Smart_Contracts

### ISSUE THREAD

**Issue by jesinnott** [buildspace/buildspace-projects#441]
Translate into spanish the Section 1 Lesson 3 of Solidity_And_Smart_Contracts.

**Comment by adilanchian** [comment]
Hey @jesinnott got you !

Thanks for tagging the issue in your PR as well :)

**Comment by emboslicev2** [comment]
Hey @jesinnott mandame un mensaje en discord (emboslice) si quieres colaborar en un "blog post" - como tu experiencia en proyectos con buildspace etc etc :)

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
