### ISSUE TITLE
Could Not Compile Solana Validator M1 Mac Solana Installation Failed

### ISSUE THREAD

**Issue by branaust** [buildspace/buildspace-projects#451]
I am going through the installation steps for M1 Users in this repo.

Terminal Command: 
`./scripts/cargo/install-all.sh`

Expected Result: Installation complete succesfully

Actual Result: The Solana instalation is very close to completing. It installs all packages up to 825/828 and fails to install the final three packages which looks to be caused by the solana validator: 

```
`Compiling solana-ledger-tool v1.8.2 (/Users/branaust/solana/ledger-tool)
   Compiling solana-validator v1.8.2 (/Users/branaust/solana/validator)
error: linking with cc failed: exit code: 1
...

error: aborting due to previous error

error: could not compile solana-validator

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: linking with cc failed: exit code: 1
`
```

Homebrew is installed. I've deleted the Solana file and tried to clone the repo again but no avail.

**Comment by sxppro** [comment]
Try using Terminal running under Rosetta and switch to the x86 macOS Rust toolchain

**Comment by adilanchian** [comment]
Thanks for the reply @sxppro  :)

@branaust - Let me bring in @NickGonzalez04 as he is our M1 guru here. He might actually already know what to do here!

**Comment by NickGonzalez04** [comment]
Hey @branaust ! I don’t know if the this is a typo on GitHub, but the command `./scripts/cargo/install-all.sh` should actually have a space period at the end like this `./scripts/cargo/install-all.sh .` 
 Wanted to double check you were doing that command first!

Thanks for reply @sxppro - cool thing with the newer version releases on Solana, you don’t have to use the Rosetta install route!

**Comment by sxppro** [comment]
> Thanks for reply @sxppro - cool thing with the newer version releases on Solana, you don’t have to use the Rosetta install route!

Woohoo thanks for the info!

**Comment by adilanchian** [comment]
Looks like this was resolved! 

Thanks for the help @NickGonzalez04  :)
