### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rafaelp** [buildspace/buildspace-projects#456]
Whats is the license of this project?

**Comment by stevedsimkins** [comment]
@adilanchian @DavidBarrick  Maybe we should add an MIT license? 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project

https://choosealicense.com/licenses/mit/

**Comment by morektz** [comment]
I can recommend the Unlicense , since I can see the content is not bound anything specific now 
https://unlicense.org/

**Comment by adilanchian** [comment]
Hi!

Someone from the community added a license :). Thanks for this !!

https://github.com/buildspace/buildspace-projects/blob/main/LICENSE
