### ISSUE TITLE
✨ [Solidity_And_Smart_Contracts : Section_1 - Lession_5] Unable to upload screenshot

### ISSUE THREAD

**Issue by siddharth2010** [buildspace/buildspace-projects#461]
### What You Are Changing
*unable to upload terminal screenshot at the end of the lession*
Clicking the button does nothing.

Screen Recording:
https://user-images.githubusercontent.com/32238400/143722462-c0afedae-7d0b-48fc-b720-297008e9077a.mov

Client details:
Mac OS | chrome | 95.0.4638

**Comment by adilanchian** [comment]
Hey @siddharth2010 !!

thanks for bringing this up :). Did you happen to see anything in your console 🤔 ?

**Comment by adilanchian** [comment]
Going to close this for now!

If you feel strongly about it it - feel free to open another issue or PR with the fix :)
