### ISSUE TITLE
✨ Solana_NFTs/en/Section_0/Lesson_2_Whats_Different_About_Solana_NFTs.md

### ISSUE THREAD

**Issue by wrongholt** [buildspace/buildspace-projects#524]
### What You Are Changing
In Ethereum this is easy. It's all synchronous and atomic so we don't need to think about that.

Shouldn't this be asynchronous? Meaning not happing at the same time?

**Comment by adilanchian** [comment]
Hey @wrongholt !
Would you be open to making this PR :eyes:

**Comment by adilanchian** [comment]
Going to close this for now :).

If you feel strongly about it feel free to open a PR for this change!
