### ISSUE TITLE
✨ [Build a Web3 App with Solidity + Ethereum Smart Contracts]: <SECTION_1> - <LESSON_5>

### ISSUE THREAD

**Issue by DrTriv** [buildspace/buildspace-projects#602]
### What You Are Changing
I believe there's an error in the code contained in the project documentation for the last lesson in section 1

In the runMain const, when there is an error, it should read "console.log(error)". It currently reads "console.error(error)"

![unknown](https://user-images.githubusercontent.com/89686262/146580761-67e83e92-4a3e-4dac-a070-a59e8e85924d.png)

**Comment by adilanchian** [comment]
Hey @DrTriv !

If you can open a PR for this and tag this issue that would be sick :)

**Comment by stevedsimkins** [comment]
Made a PR to fix this little guy :]

**Comment by adilanchian** [comment]
MUCH appreciated <3

fin!
