### ISSUE TITLE
✨ [Build your own DAO with just Javascript in a weekend]: <SECTION_3> - <Building_Treasury_And_Governance>

### ISSUE THREAD

**Issue by okorieebube** [buildspace/buildspace-projects#634]
### What You Are Changing
*The url provided for the thirdweb governance contract on github isn't correct<br/>
Its supposed to be `https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/vote/VotingGovernor.sol`
!*

**Comment by nachoiacovino** [comment]
Closed by #638

**Comment by adilanchian** [comment]
Merged in! Thanks for this :)

**Comment by okorieebube** [comment]
Sure!
