### ISSUE TITLE
✨ Solidity_And_Smart_Contracts: SECTION_3 - Lesson_1_Storing_Messages_From_Users

### ISSUE THREAD

**Issue by garricn** [buildspace/buildspace-projects#669]
### What You Are Changing
I'm not exactly sure how to make this lesson better but it was much harder than the previous lessons and not necessarily in a good way. I think the lesson falls apart at the part where it reads "Where do we call this brand new getAllWaves() function, though?". I think its good to challenge students but not everyone is at the same level. For those that want the challenge, they are free to meet it, but there should be a tip/hint/solution for those that are not able to meet it.

I also think that it would be better to post complete code snippets of files with file name and where the change should be made (Replit, Smart Contract, etc). Sometimes the Lessons mentions this explicitly but sometimes its not very clear whether we're changing the contract or website and what file we're changing and where in that file the change should be made. Links to source code would be helpful. For example, I was not able to complete this lesson without finding Alec's gists.

**Comment by adilanchian** [comment]
Hey @garricn !

Thanks for the feedback here :). It would be really helpful to see some key points on why this was difficult. Your first paragraph was a bit difficult for me to understand!

Thanks in advance :)

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
