### ISSUE TITLE
✨ [Solidity_And_Smart_Contracts]: <SECTION_1> - <Lesson_3_Compile_Contract_Locally> Spanish translations populate English site

### ISSUE THREAD

**Issue by dfimbres** [buildspace/buildspace-projects#732]
### Spanish translations populate english site
This effects the page linked here. The site seems to auto populate the Spanish translations.

https://app.buildspace.so/projects/CO02cf0f1c-f996-4f50-9669-cf945ca3fb0b/lessons/LEc9263031-fd3e-4af8-8f12-d366099bfe8a

**Comment by adilanchian** [comment]
<333 ty!

Currently working on a way to implement this!!
