### ISSUE TITLE
✨ Mint your own NFT collection and ship a Web3 app to show them off: SECTION_1 - 💎 Create a contract that mints NFTs

### ISSUE THREAD

**Issue by PhoeniXAbhisheK** [buildspace/buildspace-projects#779]
### What You Are Changing
For the project(s) that use `import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";` and then inhert `ERC721URIStorage`, the compilation breaks. This is caused because previously the import was `import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";` and changing back to this works,
![image](https://user-images.githubusercontent.com/16290904/148657118-2930a2d8-5c2c-4697-8b72-205ed885a1b7.png)

### Anything else?
Was added via below PR merge.
https://github.com/buildspace/buildspace-projects/pull/740

**Comment by charles-vj** [comment]
I would like to take up this issue. Faced the same problem, and importing the correct sol file should do the trick

**Comment by richiehydra** [comment]
contract MyStupidNFT is ERC721
{
//code here...
}

these might solve ur issuue!!

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
