### ISSUE TITLE
✨ [Build a Web3 App with Solidity + Ethereum Smart Contracts]: <SECTION_2> - <Setup a basic react app, setup Metamask>

### ISSUE THREAD

**Issue by AvachaBay** [buildspace/buildspace-projects#783]
### What You Are Changing
Change **Submit Link To Your Replit Site** to **Submit site screenshot**  for those who develop locally

### Anything else?
Other suggestion in my comment on gist:
https://gist.github.com/adilanchian/9f745fdfa9186047e7a779c02f4bffb7#gistcomment-4022427

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
