### ISSUE TITLE
✨ [NFT_COLLECTION]: <SECTION_5> - <Finishing touches to web app>

### ISSUE THREAD

**Issue by thomastraum** [buildspace/buildspace-projects#82]
### What You Are Changing
leave more "food for thought" for the hungry, more pointers to going deeper and more pro.

- how to charge for mint? 
- how to add a creator fee for resale? 
- how to use hardhat and web3 / ethers and run it locally instead of rinkeby. I got pretty far with that.... but hit an error.
-- there is some cool stuff like npx hardhat node to run a local development you could at least hint at. 
- how to map the number of possible combinations to the number of nfts available and make sure that there will never be a duplicate, that could be cool

**Comment by adilanchian** [comment]
Heckkkk ya :). Thanks so much for this!! 

Are you looking for this information to be included in the lesson or just some "food for thought" as you stated?

**Comment by thomastraum** [comment]
if you can fit it in the lesson even better! it's up to you whether it's TMI for the beginners I guess. 
I think the solidity questions are the most difficult for everyone since the web dev part is easier to google, but solidity is quite a jump for normal web devs I feel. 

I think local hardhat would be good as its good for fast iteration, and a pretty neat feature you might not be aware of. I used truffle before but hardhat seems so much cooler.

**Comment by thomastraum** [comment]
sure no probs.
however, I dont have the answers to these questions, if not I wouldnt 
have asked them, so I am not the right person to do a PR.

T


Alec Dilanchian wrote on 10/11/2021 2:55 PM:

**Comment by adilanchian** [comment]
Had a few PRs merged in here that address this! Going to close :)

Thank you!!
