### ISSUE TITLE
✨ [Solidity + Ethereum Smart Contracts]: <SECTION_2> - <Call the our deployed smart contract from our web app>

### ISSUE THREAD

**Issue by flamerged** [buildspace/buildspace-projects#858]
### What You Are Changing
I just wanted to give a short and quick suggestion for the imported abi. Because the JSON is essentially an object you can use destructuring and renaming to import the abi, like: 

```JavaScript
import { abi as contractABI } from './utils/WavePortal.json'
``` 

What do you think? Works for me

**Comment by richiehydra** [comment]
Cool glad to see such stuffs!!!

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
