### ISSUE TITLE
✨ [Build a web3 app on solana]: <SECTION_2> - <Get local solana env running>

### ISSUE THREAD

**Issue by HodeX7** [buildspace/buildspace-projects#914]
when I run this command the following error pops up and after i write ' solana --version ' it says "zsh: command not found: solana"

Please help me fix this.
./scripts/cargo-install-all.sh .
./scripts/cargo-install-all.sh: line 12: greadlink: command not found
Install location: /Users/aksharmehta/solana (release)
Note: Performance libraries are only available for Linux
+ '' build --release --bin solana --bin solana-bench-exchange --bin solana-bench-tps --bin solana-faucet --bin solana-gossip --bin solana-install --bin solana-keygen --bin solana-ledger-tool --bin solana-log-analyzer --bin solana-net-shaper --bin solana-sys-tuner --bin solana-validator --bin cargo-build-bpf --bin cargo-test-bpf --bin solana-dos --bin solana-install-init --bin solana-stake-accounts --bin solana-test-validator --bin solana-tokens --bin solana-watchtower --bin solana-genesis
./scripts/cargo-install-all.sh: line 130: : command not found

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
