### ISSUE TITLE
✨ [Solana_NFTs]: <SECTION_3> - <LESSON 2> Replace machineState (it's no longer exist) to candyMachine

### ISSUE THREAD

**Issue by jte0711** [buildspace/buildspace-projects#920]
### What You Are Changing
Problem:
- on line `146-156`, it uses `machineState` but it's not defined, and when I look at the previous render before this changes, it uses `candyMachine` instead (which works well).

Solution:
- Replace `machineState` with `candyMachine`. 

### Anything else?
*Any other thoughts or concerns? Let us know!*

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
