### ISSUE TITLE
✨ [Solana_NFTs]: <SECTION_3> - <Lesson 1> candyMachine mentioned before it is defined.

### ISSUE THREAD

**Issue by jte0711** [buildspace/buildspace-projects#922]
### What You Are Changing
Problems:
- `candyMachine` mentioned in the code before the state is defined, this leads to some errors and confusion to some readers because the lessons (in 🍪 Render the retrieved data.) said that if we refresh the page it will show us some logs but instead we got error. 

Solution:
- We can either initialise the state for `candyMachine` from the beginning or move the part (line 241-247) after the part where we add state for `candyMachine` (line 273)

### Anything else?
*Any other thoughts or concerns? Let us know!*

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
