### ISSUE TITLE
✨ [Polygon_ENS]: [Section 1] - [Lesson_3_Setup_Domains_Resolvers_Records]

### ISSUE THREAD

**Issue by oashtari** [buildspace/buildspace-projects#948]
### What You Are Changing

In the final section of this lesson: "Test Other Users", the const of `domainOwner' (used in prior sections above) is suddenly changed to 'domainAddress' -- unless I missed a reason for this change, would be good to make them consistent.

**Comment by Azizadx** [comment]
Also, there's a minor mistake in the first part of the lesson which is the screenshot. it could be confused for some people 
 
<img width="957" alt="Screen Shot 2022-02-22 at 5 33 25 PM" src="https://user-images.githubusercontent.com/45791956/155153753-1b483656-3144-4cf4-8d72-52c535f1af90.png">

- "yo yo I am a contract and I am smart "   is not define in begin of lesson as shown letcutre 
<img width="620" alt="Screen Shot 2022-02-22 at 5 34 31 PM" src="https://user-images.githubusercontent.com/45791956/155154602-3727b365-642a-4a28-afdb-af85ca884b04.png">


-  Also there's on last ouptut is should retrieve the domain address only 
 <img width="641" alt="Screen Shot 2022-02-22 at 5 33 45 PM" src="https://user-images.githubusercontent.com/45791956/155154379-eb4432af-1164-4e72-91d2-00ffa7eb7f4b.png">


- This output In my terminal 
<img width="645" alt="Screen Shot 2022-02-22 at 5 26 49 PM" src="https://user-images.githubusercontent.com/45791956/155154229-0e2e2e22-43ea-498b-964d-3219bbc5edd5.png">

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
