### ISSUE TITLE
✨ [Polygon_ENS]: <SECTION_1> - <LESSON_4_Sell_Domains_as_NFTs>

### ISSUE THREAD

**Issue by oashtari** [buildspace/buildspace-projects#949]
### What You Are Changing
Usually when you all new code, it is designated with some sort of comment, but when this code is added (getting paid and going ninja section), there isn't a note, so it's easy to miss. 

  const balance = await hre.ethers.provider.getBalance(domainContract.address);
  console.log("Contract balance:", hre.ethers.utils.formatEther(balance));

### Anything else?
thanks for everything you do, sorry for me being a stickler for consistency

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
